"""Emit NodeIR definitions as committed .py modules under civitai_comfy_nodes/generated/."""

from pathlib import Path

from .ir import FieldIR, NodeIR, OutputIR, snake_case

RETURN_TYPE_BY_KIND = {
    "image": ("IMAGE",),
    "image_list": ("IMAGE",),
    "video": ("VIDEO",),
    "audio": ("AUDIO",),
    "audio_or_video": ("AUDIO", "VIDEO"),
    "string": ("STRING",),
    "json": ("STRING",),
}

API_CONFIG_INPUT = (
    '"api_config": ("CIVITAI_CONFIG", {"tooltip": '
    '"Optional Civitai Auth connection; defaults to CIVITAI_API_TOKEN or stored OAuth login."})'
)


def header(spec_sha: str) -> str:
    return (
        f"# AUTO-GENERATED by codegen/generate.py from spec/v2-consumers.json (sha256: {spec_sha}).\n"
        "# DO NOT EDIT — adjust codegen/overrides.json and re-run scripts/sync-spec.sh instead.\n"
    )


def return_slots(outputs: list[OutputIR]) -> tuple[list[str], list[str]]:
    types: list[str] = []
    names: list[str] = []
    for output in outputs:
        slot_types = RETURN_TYPE_BY_KIND[output.kind]
        base = snake_case(output.api)
        if output.kind == "audio_or_video":
            names.extend([f"{base}_audio", f"{base}_video"])
        else:
            names.append(base)
        types.extend(slot_types)
    types.extend(["STRING", "STRING"])
    names.extend(["workflow_id", "raw_json"])
    return types, names


def emit_field_entry(field: FieldIR) -> str:
    if isinstance(field.comfy_type, list):
        type_expr = repr(field.comfy_type)
    else:
        type_expr = f'"{field.comfy_type}"'
    return f'"{field.widget}": ({type_expr}, {repr(field.options)})'


def emit_node(node: NodeIR) -> str:
    return_types, return_names = return_slots(node.outputs)
    required = [f for f in node.fields if f.required]
    optional = [f for f in node.fields if not f.required]

    fields_entries = ",\n        ".join(f'"{f.widget}": F("{f.api}", "{f.kind}")' for f in node.fields)
    outputs_entries = ", ".join(f'O("{o.api}", "{o.kind}")' for o in node.outputs)
    required_entries = ",\n                ".join(emit_field_entry(f) for f in required)
    optional_entries = ",\n                ".join([*(emit_field_entry(f) for f in optional), API_CONFIG_INPUT])

    lines = [f"class {node.class_name}(CivitaiRecipeNodeBase):"]
    lines.append(f'    """{node.display_name} — {node.description}."""')
    lines.append("")
    for warning in node.warnings:
        lines.append(f"    # codegen warning: {warning}")
    lines.append(f'    RECIPE = "{node.recipe}"')
    lines.append(f'    STEP_TYPE = "{node.step_type}"')
    if node.discriminator:
        lines.append(f"    DISCRIMINATOR = {node.discriminator!r}")
    lines.append(f'    CATEGORY = "{node.category}"')
    lines.append('    FUNCTION = "run"')
    lines.append(f"    RETURN_TYPES = {tuple(return_types)!r}")
    lines.append(f"    RETURN_NAMES = {tuple(return_names)!r}")
    lines.append("    FIELDS = {")
    if fields_entries:
        lines.append(f"        {fields_entries},")
    lines.append("    }")
    lines.append(f"    OUTPUTS = ({outputs_entries}{',' if node.outputs else ''})")
    lines.append("")
    lines.append("    @classmethod")
    lines.append("    def INPUT_TYPES(cls):")
    lines.append("        return {")
    lines.append('            "required": {')
    if required_entries:
        lines.append(f"                {required_entries},")
    lines.append("            },")
    lines.append('            "optional": {')
    lines.append(f"                {optional_entries},")
    lines.append("            },")
    lines.append("        }")
    return "\n".join(lines)


def emit_module(nodes: list[NodeIR], spec_sha: str) -> str:
    parts = [
        header(spec_sha),
        "from ..base import CivitaiRecipeNodeBase, F, O",
        "",
        "",
    ]
    parts.append("\n\n\n".join(emit_node(node) for node in nodes))
    parts.append("")
    parts.append("")
    parts.append("NODE_CLASS_MAPPINGS = {")
    for node in nodes:
        parts.append(f'    "{node.class_name}": {node.class_name},')
    parts.append("}")
    parts.append("")
    parts.append("NODE_DISPLAY_NAME_MAPPINGS = {")
    for node in nodes:
        parts.append(f'    "{node.class_name}": "{node.display_name}",')
    parts.append("}")
    parts.append("")
    return "\n".join(parts)


def emit_init(module_names: list[str], spec_sha: str) -> str:
    parts = [header(spec_sha)]
    parts.append(f"from . import {', '.join(module_names)}")
    parts.append("")
    parts.append("NODE_CLASS_MAPPINGS = {")
    for name in module_names:
        parts.append(f"    **{name}.NODE_CLASS_MAPPINGS,")
    parts.append("}")
    parts.append("")
    parts.append("NODE_DISPLAY_NAME_MAPPINGS = {")
    for name in module_names:
        parts.append(f"    **{name}.NODE_DISPLAY_NAME_MAPPINGS,")
    parts.append("}")
    parts.append("")
    return "\n".join(parts)


def write_modules(nodes: list[NodeIR], output_dir: Path, spec_sha: str) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    for stale in output_dir.glob("*.py"):
        stale.unlink()

    by_module: dict[str, list[NodeIR]] = {}
    for node in nodes:
        by_module.setdefault(node.module, []).append(node)

    module_names = sorted(by_module)
    for name in module_names:
        (output_dir / f"{name}.py").write_text(emit_module(by_module[name], spec_sha))
    (output_dir / "__init__.py").write_text(emit_init(module_names, spec_sha))
